// THIS FILE IS AUTOMATICALLY GENERATED.
// DO NOT EDIT IT DIRECTLY. EDIT tool/make-meta INSTEAD.

final class Meta {
    static const VERSION_STRING   = "0.9.17";
    static const VERSION_NUMBER   =  0.009017;
    static const LAST_COMMIT_HASH = "7b65dcbd073de4267fd12dc27470c71e46c48c95";
    static const LAST_COMMIT_DATE = "2013-03-19 12:04:46 +0900";

    static const IDENTIFIER = Meta.VERSION_STRING + " (" + Meta.LAST_COMMIT_DATE + "; " + Meta.LAST_COMMIT_HASH + ")";
} // class Meta
