// THIS FILE IS AUTOMATICALLY GENERATED.
// DO NOT EDIT IT DIRECTLY. EDIT tool/make-meta INSTEAD.

final class Meta {
    static const VERSION_STRING   = "0.9.25";
    static const VERSION_NUMBER   =  0.009025;
    static const LAST_COMMIT_HASH = "3356329969db62d9460092da3ad9eecf395e8394";
    static const LAST_COMMIT_DATE = "2013-04-14 14:20:46 +0900";

    static const IDENTIFIER = Meta.VERSION_STRING + " (" + Meta.LAST_COMMIT_DATE + "; " + Meta.LAST_COMMIT_HASH + ")";
} // class Meta
